apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api-deployment
  template:
    metadata:
      labels:
        type: api-deployment
    spec:
      containers:
        - name: dp-api
          image: duynguyenngoc/dp-api:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8081
          command: 

---
apiVersion: v1
kind: Service
metadata:
  name: dp-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: api-deployment