apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploymemt
spec:
  selector:
    matchLabels:
      app: redis-deploymemt
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-deploymemt
    spec:
      containers:
        - name: redis-deploymemt
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server", "--requirepass", "1q2w3e4r", "--bind", "0.0.0.0", "--port", "6379"]

---
apiVersion: v1
kind: Service
metadata:
  name: db-redis
spec:
  # type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    type: redis-deploymemt