apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: dp

spec:
  replicas: 1
  selector:
    matchLabels:
      type: rabbitmq-pod
      app: dp
  template:
    metadata:
      name: dp-rabbitmq-pod
      labels:
        type: rabbitmq-pod
        app: dp
    spec:
      containers:
        - name: dp-rabbitmq
          image: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "1q2w3e4r"
          ports:
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    type: dp-rabbitmq-service
    app: dp
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    type: rabbitmq-pod
    app: dp