name:  PRODUCTION_PIPELINE
on:
  push:
    branches:
    - main 
    # paths:
    # - "dp-api/**" 
env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DP_API_IMAGE: duynguyenngoc/dp-api:latest
  DP_PARAGRAPH_IMAGE: duynguyenngoc/dp-paragraph:latest

jobs:
    build-dp-api:
      name: Building dp-api
      runs-on: ubuntu-latest
      steps:  

      # [Step-1] check config git
      - uses: actions/checkout@v2

      # [Step-2] login dockerhub container
      - name: Login to DockerHub Registry
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      
      # [Step-3] buid and tag image from Dockerfile
      - name: Build docker image
        run: |
          docker build -t $DP_API_IMAGE ./dp-api/
      
      # [Step-4] Push image to docker hub
      - name: Push image to DockerHub
        run: |
          docker push $DP_API_IMAGE

    build-dp-paragraph:
      name: Building dp-paragraph
      runs-on: ubuntu-latest
      steps:  

      # [Step-1] check config git
      - uses: actions/checkout@v2

      # [Step-2] login dockerhub container
      - name: Login to DockerHub Registry
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      
      # [Step-3] buid and tag image from Dockerfile
      - name: Build docker image
        run: |
          docker build -t $DP_PARAGRAPH_IMAGE ./dp-paragraph/
      
      # [Step-4] Push image to docker hub
      - name: Push image to DockerHub
        run: |
          docker push $DP_PARAGRAPH_IMAGE