name: DEPLOY_TO_GKE_PRODUCTION
on:
  push:
    branches:
      - main

env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} # dockerhub pass
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} # dockerhub user
  GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }} # gke project_id
  GKE_CLUSTER: cluster-document-processing # Add your cluster name here.
  GKE_ZONE: asia-south1-a  # Add your cluster zone here.
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }} # gke sa key
  DEPLOYMENT_NAME: gke-production # development name
  DP_API_IMAGE: duynguyenngoc/dp-api:latest # Image docker


jobs:
  setup-build-publish-deploy-dp-api:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:

      # # [Step-1] check config git
      # - name: Checkout
      #   uses: actions/checkout@v2

      # # [Step-2] login dockerhub container
      # - name: Login to DockerHub Registry
      #   run: |
      #     echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
      # # [Step-3] buid and tag image from Dockerfile
      # - name: Build docker image
      #   run: |
      #     docker build -t $DP_API_IMAGE ./dp-api/
      
      # # [Step-4] Push image to docker hub
      # - name: Push image to DockerHub
      #   run: |
      #     docker push $DP_API_IMAGE

      # [Step-5] Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: $GKE_SA_KEY
          project_id: $GKE_PROJECT_ID

      # [Step-6] Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # [Step-7] Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: $GKE_CLUSTER
          location: $GKE_ZONE
          credentials: $GKE_SA_KEY
      
      # [Step-8] Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize edit set image $DP_API_IMAGE
          ./kustomize build . | kubectl apply -f /o-k8s/dp-api.yaml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
    